# Generated by Django 3.2 on 2024-09-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneo4j', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
